### ISSUE TITLE
from jira 876

### ISSUE THREAD

**Issue by maxAtSW** [Conjurinc-workato-dev/ldap-sync#18]
##description
Steps to reproduce:

Current Results:

Expected Results:

Error Messages:

Logs:

Other Symptoms:

Tenant ID / Pod Number:
##Found in version
11.5

##Workaround Complexity
No workaround

##Workaround Description
sssssssssssssss

##Link to JIRA bug
https://ca-il-jira-test.il.cyber-ark.com/browse/ONYX-6572

**Comment by maxAtSW** [comment]
https://ca-il-jira-test.il.cyber-ark.com/browse/ONYX-6572

**Comment by maxAtSW** [comment]
//Author: Avigad.Maoz@cyberark.com

jira

**Comment by avigadmaoz** [comment]
gh
